### ISSUE TITLE
The handling of authors is broken

### ISSUE THREAD

**Issue by stof** [Jleagle/php-packages.com#2]
Currently, an author is identified by its email address and deduplicated. However, this is wrong:
- the email is optional for authors in Composer, and it is often the case when adding the community as an author with a link to the list of contributors on github or elsewhere (I know many packages doing it, including Symfony). Any author without email is currently missing in the display as it is ignored in https://github.com/Jleagle/reverse-packagist/blob/a6e543516e455070ef525f81359072b82f118d32/app/controllers/PackagesController.php#L269 (Packagist only ignores authors when both the email and the name are missing, allowing to support this use case, so your site should do the same)
- the same email address can be associated to different properties in different packages. In particular, the `role` property is likely to change from package to package. Packagist suffered from this bug as well, but this has been fixed in https://github.com/composer/packagist/commit/b1fdc21a5049931f34a2ebda4372d91ba52de0f4

**Comment by Jleagle** [comment]
Hi stof, i finally got around to looking at this issue and think it is correct how it is. On php-packages, i record the author data not only to show on the package page but also to use in search. I need to group the authors by the physical person, this way when you search for a particular author you only get the one person returned along with every package they are an author of. Otherwise if your role was different on 5 packages, when you searched for yourself you would get back 5 different authors with the same name and email.
